### ISSUE TITLE
URI Too Long & Broken Pipe

### ISSUE THREAD

**Issue by bleak183** [David-Moreira/JellyseerrSync#1]
Hey man, I am really excited to try this out but I am getting the following outputs (10.8.11):

Upon restarting Jellyfin and visiting /syncdeleted/movies

```Processing Deleted Movies Sync...
Total Jellyseerr Movies found as Available: 854
An error has occurred: 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 414 (URI Too Long).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__SyncDeletedMovies|8>d.MoveNext() in /src/Program.cs:line 166
```
And then, upon reloading /syncdeleted/movies

```
Processing Deleted Movies Sync...
Total Jellyseerr Movies found as Available: 854
An error has occurred: 
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.WriteByteSlowAsync(Byte b, Boolean async)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.WriteByteSlowAsync(Byte b, Boolean async)
   at System.Net.Http.HttpConnection.WriteStringAsyncSlow(String s, Boolean async)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.WriteStringAsyncSlow(String s, Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.WriteByteSlowAsync(Byte b, Boolean async)
   at System.Net.Http.HttpConnection.WriteStringAsyncSlow(String s, Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__SyncDeletedMovies|8>d.MoveNext() in /src/Program.cs:line 166
```

Radarr/Sonarr webhooks connect and test fine, however.

**Comment by David-Moreira** [comment]
Hello @bleak117 
As a fellow self hosted, really happy this could help out somehow. :)

I put this together over the course of a day, so there's certainly room for improvements. While it's working for my setup I wouldn't be surprised if there are subtle bugs for other people's environments. 

I will see if I can figure out the error you're having in **syncdeleted/movies** and improve it. :)

**Comment by mangurk** [comment]
Feel free to let me know if you need anything on my end!

**Comment by David-Moreira** [comment]
> Feel free to let me know if you need anything on my end!

Thanks! I think I just figured out the problem.
You have quite some movies on your jellyseer, **854**!
Basically the app then queries jellyfin with their ids to try and figure out if they really exist in jellyfin. It currently does this in a single call, with an url like this:
**{jellyfinurl}/Items?ids={movieId1,movieId2,...}** So since you have 854 movies, you can see what's happening haha. I don't have as many on my end haha.

I will work on a fix by batching into several requests.

**Comment by David-Moreira** [comment]
Hello @bleak117 
The image has now been updated with the fix.
Please let me know if it worked correctly. 

Cheers.

**Comment by mangurk** [comment]
I'm getting this now:

```Processing Deleted Movies Sync...
An error has occurred: 
System.UriFormatException: Invalid URI: Invalid port specified.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__0(HttpClient client) in /src/Program.cs:line 26
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__SyncDeletedMovies|8>d.MoveNext() in /src/Program.cs:line 150```

**Comment by David-Moreira** [comment]
That's a shame. Can you post how you've configured your urls? (you can ommit any names or ips if sensible)

**Comment by David-Moreira** [comment]
Oh I just remembered I wrote the calls assuming endpoints that end in a **/**. I didn't bother writign the code to check it.
So both your urls should end in a **/**

Like this:
```
  "JELLYFIN_HOST_URL": "http://192.168.1.10:8096/",
  "JELLYSEERR_HOST_URL": "http://192.168.1.11:5055/"
```
Could that possibly be your problem?

**Edit:** Opened #3 so I can fix this at a later date, for any future user. If this is your problem please use **/** in the end while I don't get around to fixing it. Thanks!

**Comment by mangurk** [comment]
That was it!!!! Man, I have been waiting for MONTHS for a fix for this. You're a legend ❤️

**Comment by David-Moreira** [comment]
Haha, that's great! I was also finding this to be a feature I lacked on my Jellyseerr instance. 
Hopefully the maintainer of Jellyseerr will get to it eventually. But for now I guess this works.

See you around, man.

**Comment by mangurk** [comment]
Hey man, just thought I'd let you know the Webhook functionality doesn't seem to be working... If I go to /syncdeleted/movies then it works fine. But if I delete a movie from my Jellyfin library and then update Radarr, when it gets marked as "missing" nothing really happens. Even if I delete the movie from Radarr nothing happens.
